FROM python:3.6

COPY src/ /main
RUN pip install --upgrade pip
workdir /main
COPY . .
RUN apt-get update
RUN apt-get install python-pip -y
COPY Docker/requirements.txt requirements.txt
RUN python -m pip install -U -r requirements.txt
RUN apt-get install ffmpeg libsm6 libxext6  -y

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4343"]

